name: kk-admin

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # Step 1: Checkout master branch
      - name: 1. 检查master分支
        uses: actions/checkout@master

      # Step 2: Set up Node.js
      - name: 2. 设置Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Cache node_modules
      - name: 3. 缓存
        uses: actions/cache@master
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      # Step 4: Install dependencies if cache is not hit
      - name: 4. 安装插件
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install

      # Step 5: Build the project
      - name: 5. 生成页面并压缩
        env:
          TZ: Asia/Shanghai
          VITE_GLOB_API_URL: ${{ secrets.VITE_GLOB_API_URL }}
          VITE_GLOB_UPLOAD_URL: ${{ secrets.VITE_GLOB_UPLOAD_URL }}
          VITE_GLOB_UPLOAD_TOKEN: ${{ secrets.VITE_GLOB_UPLOAD_TOKEN }}
          VITE_GLOB_APP_TITLE: ${{ secrets.VITE_GLOB_APP_TITLE }}
        run: yarn run build

      # Step 6: Deploy to vercel branch
      - name: 6. 推送到vercel分支
        uses: peaceiris/actions-gh-pages@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: vercel
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: ${{ github.event.head_commit.message }}
